export const TEAMS = [
  'Arsenal',
  'Aston Villa',
  'Brentford',
  'Brighton and Hove Albion',
  'Burnley',
  'Chelsea',
  'Crystal Palace',
  'Everton',
  'Fulham',
  'Liverpool',
  'Leeds United',
  'Manchester City',
  'Manchester United',
  'Newcastle United',
  'Nottingham Forest',
  'Sunderland',
  'Tottenham Hotspur',
  'West Ham United',
  'Wolverhampton Wanderers',
  'Bournemouth',
    // Serie A
  'AC Milan',
  'Atalanta',
  'Bologna',
  'Cagliari',
  'Como',
  'Cremonese',
  'Fiorentina',
  'Genoa',
  'Inter',
  'Juventus',
  'Lazio',
  'Lecce',
  'Napoli',
  'Parma',
  'Pisa',
  'Roma',
  'Sassuolo',
  'Torino',
  'Udinese',
  'Hellas Verona',

// La Liga 2025/26
'Deportivo Alaves',
'Ath. Bilbao',
'Atletico Madrid',
'Barcelona',
'Celta Vigo',
'Elche',
'Espanyol',
'Getafe',
'Girona',
'Levante',
'Mallorca',
'Osasuna',
'Rayo Vallecano',
'Real Betis',
'Real Madrid',
'Real Oviedo',
'Real Sociedad',
'Seville',
'Valencia',
'Villarreal',


// Ligue 1 - 2025/26
'Angers',
'Auxerre',
'Brest',
'Le Havre',
'Lens',
'Lille',
'Lorient',
'Olympique de Lyon',
'Olympique de Marseille',
'Metz',
'Monaco',
'Nantes',
'Nice',
'Paris FC',
'Paris Saint-Germain',
'Rennes',
'Strasbourg',
'Toulouse',

  // Bundesliga
  'Augsburg',
  'Bayer Leverkusen',
  'Bayern Munich',
  'Borussia Dortmund',
  'Borussia Mönchengladbach',
  'Eintracht Frankfurt',
  'Freiburg',
  'Heidenheim',
  'Hoffenheim',
  'Koln',
  'Mainz',
  'RB Leipzig',
  'Stuttgart',
  'Union Berlin',
  'Werder Bremen',
  'Wolfsburg',
  'Hamburg',
  'St Pauli',

    // Pays-Bas
  'PSV Eindhoven', 'Ajax Amsterdam',

  // Portugal
  'Sporting CP',

  // Belgique
  'Union SG',

  // Turquie
  'Galatasaray SK',

  // Tchéquie
  'Slavia Prague',
];
